/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dbsystem.cotizatuvehiculo.model.impl;

import com.dbsystem.cotizatuvehiculo.model.ConcesionarioVehiculo;
import com.dbsystem.cotizatuvehiculo.model.ConcesionarioVehiculoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the ConcesionarioVehiculo service. Represents a row in the &quot;dbsystem_ConcesionarioVehiculo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ConcesionarioVehiculoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConcesionarioVehiculoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConcesionarioVehiculoImpl
 * @generated
 */
@ProviderType
public class ConcesionarioVehiculoModelImpl
	extends BaseModelImpl<ConcesionarioVehiculo>
	implements ConcesionarioVehiculoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a concesionario vehiculo model instance should use the <code>ConcesionarioVehiculo</code> interface instead.
	 */
	public static final String TABLE_NAME = "dbsystem_ConcesionarioVehiculo";

	public static final Object[][] TABLE_COLUMNS = {
		{"concesionarioVehiculoId", Types.BIGINT},
		{"concesionarioId", Types.BIGINT}, {"vehiculoId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("concesionarioVehiculoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("concesionarioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vehiculoId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dbsystem_ConcesionarioVehiculo (concesionarioVehiculoId LONG not null primary key,concesionarioId LONG,vehiculoId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table dbsystem_ConcesionarioVehiculo";

	public static final String ORDER_BY_JPQL =
		" ORDER BY concesionarioVehiculo.concesionarioVehiculoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dbsystem_ConcesionarioVehiculo.concesionarioVehiculoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CONCESIONARIOID_COLUMN_BITMASK = 1L;

	public static final long VEHICULOID_COLUMN_BITMASK = 2L;

	public static final long CONCESIONARIOVEHICULOID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ConcesionarioVehiculoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _concesionarioVehiculoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConcesionarioVehiculoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _concesionarioVehiculoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConcesionarioVehiculo.class;
	}

	@Override
	public String getModelClassName() {
		return ConcesionarioVehiculo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ConcesionarioVehiculo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ConcesionarioVehiculo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcesionarioVehiculo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ConcesionarioVehiculo)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ConcesionarioVehiculo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ConcesionarioVehiculo, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ConcesionarioVehiculo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ConcesionarioVehiculo, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ConcesionarioVehiculo, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ConcesionarioVehiculo, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ConcesionarioVehiculo, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ConcesionarioVehiculo, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ConcesionarioVehiculo, Object>>();
		Map<String, BiConsumer<ConcesionarioVehiculo, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ConcesionarioVehiculo, ?>>();

		attributeGetterFunctions.put(
			"concesionarioVehiculoId",
			ConcesionarioVehiculo::getConcesionarioVehiculoId);
		attributeSetterBiConsumers.put(
			"concesionarioVehiculoId",
			(BiConsumer<ConcesionarioVehiculo, Long>)
				ConcesionarioVehiculo::setConcesionarioVehiculoId);
		attributeGetterFunctions.put(
			"concesionarioId", ConcesionarioVehiculo::getConcesionarioId);
		attributeSetterBiConsumers.put(
			"concesionarioId",
			(BiConsumer<ConcesionarioVehiculo, Long>)
				ConcesionarioVehiculo::setConcesionarioId);
		attributeGetterFunctions.put(
			"vehiculoId", ConcesionarioVehiculo::getVehiculoId);
		attributeSetterBiConsumers.put(
			"vehiculoId",
			(BiConsumer<ConcesionarioVehiculo, Long>)
				ConcesionarioVehiculo::setVehiculoId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getConcesionarioVehiculoId() {
		return _concesionarioVehiculoId;
	}

	@Override
	public void setConcesionarioVehiculoId(long concesionarioVehiculoId) {
		_concesionarioVehiculoId = concesionarioVehiculoId;
	}

	@Override
	public long getConcesionarioId() {
		return _concesionarioId;
	}

	@Override
	public void setConcesionarioId(long concesionarioId) {
		_columnBitmask |= CONCESIONARIOID_COLUMN_BITMASK;

		if (!_setOriginalConcesionarioId) {
			_setOriginalConcesionarioId = true;

			_originalConcesionarioId = _concesionarioId;
		}

		_concesionarioId = concesionarioId;
	}

	public long getOriginalConcesionarioId() {
		return _originalConcesionarioId;
	}

	@Override
	public long getVehiculoId() {
		return _vehiculoId;
	}

	@Override
	public void setVehiculoId(long vehiculoId) {
		_columnBitmask |= VEHICULOID_COLUMN_BITMASK;

		if (!_setOriginalVehiculoId) {
			_setOriginalVehiculoId = true;

			_originalVehiculoId = _vehiculoId;
		}

		_vehiculoId = vehiculoId;
	}

	public long getOriginalVehiculoId() {
		return _originalVehiculoId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ConcesionarioVehiculo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConcesionarioVehiculo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ConcesionarioVehiculo)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConcesionarioVehiculoImpl concesionarioVehiculoImpl =
			new ConcesionarioVehiculoImpl();

		concesionarioVehiculoImpl.setConcesionarioVehiculoId(
			getConcesionarioVehiculoId());
		concesionarioVehiculoImpl.setConcesionarioId(getConcesionarioId());
		concesionarioVehiculoImpl.setVehiculoId(getVehiculoId());

		concesionarioVehiculoImpl.resetOriginalValues();

		return concesionarioVehiculoImpl;
	}

	@Override
	public int compareTo(ConcesionarioVehiculo concesionarioVehiculo) {
		long primaryKey = concesionarioVehiculo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ConcesionarioVehiculo)) {
			return false;
		}

		ConcesionarioVehiculo concesionarioVehiculo =
			(ConcesionarioVehiculo)obj;

		long primaryKey = concesionarioVehiculo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ConcesionarioVehiculoModelImpl concesionarioVehiculoModelImpl = this;

		concesionarioVehiculoModelImpl._originalConcesionarioId =
			concesionarioVehiculoModelImpl._concesionarioId;

		concesionarioVehiculoModelImpl._setOriginalConcesionarioId = false;

		concesionarioVehiculoModelImpl._originalVehiculoId =
			concesionarioVehiculoModelImpl._vehiculoId;

		concesionarioVehiculoModelImpl._setOriginalVehiculoId = false;

		concesionarioVehiculoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ConcesionarioVehiculo> toCacheModel() {
		ConcesionarioVehiculoCacheModel concesionarioVehiculoCacheModel =
			new ConcesionarioVehiculoCacheModel();

		concesionarioVehiculoCacheModel.concesionarioVehiculoId =
			getConcesionarioVehiculoId();

		concesionarioVehiculoCacheModel.concesionarioId = getConcesionarioId();

		concesionarioVehiculoCacheModel.vehiculoId = getVehiculoId();

		return concesionarioVehiculoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ConcesionarioVehiculo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ConcesionarioVehiculo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcesionarioVehiculo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((ConcesionarioVehiculo)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ConcesionarioVehiculo, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ConcesionarioVehiculo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcesionarioVehiculo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((ConcesionarioVehiculo)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		ConcesionarioVehiculo.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		ConcesionarioVehiculo.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _concesionarioVehiculoId;
	private long _concesionarioId;
	private long _originalConcesionarioId;
	private boolean _setOriginalConcesionarioId;
	private long _vehiculoId;
	private long _originalVehiculoId;
	private boolean _setOriginalVehiculoId;
	private long _columnBitmask;
	private ConcesionarioVehiculo _escapedModel;

}