/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dbsystem.cotizatuvehiculo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ciudades service. Represents a row in the &quot;dbsystem_Ciudades&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dbsystem.cotizatuvehiculo.model.impl.CiudadesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dbsystem.cotizatuvehiculo.model.impl.CiudadesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ciudades
 * @generated
 */
@ProviderType
public interface CiudadesModel extends BaseModel<Ciudades> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ciudades model instance should use the {@link Ciudades} interface instead.
	 */

	/**
	 * Returns the primary key of this ciudades.
	 *
	 * @return the primary key of this ciudades
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ciudades.
	 *
	 * @param primaryKey the primary key of this ciudades
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ciudad ID of this ciudades.
	 *
	 * @return the ciudad ID of this ciudades
	 */
	public long getCiudadId();

	/**
	 * Sets the ciudad ID of this ciudades.
	 *
	 * @param ciudadId the ciudad ID of this ciudades
	 */
	public void setCiudadId(long ciudadId);

	/**
	 * Returns the ciudad of this ciudades.
	 *
	 * @return the ciudad of this ciudades
	 */
	@AutoEscape
	public String getCiudad();

	/**
	 * Sets the ciudad of this ciudades.
	 *
	 * @param ciudad the ciudad of this ciudades
	 */
	public void setCiudad(String ciudad);

	/**
	 * Returns the estado of this ciudades.
	 *
	 * @return the estado of this ciudades
	 */
	public boolean getEstado();

	/**
	 * Returns <code>true</code> if this ciudades is estado.
	 *
	 * @return <code>true</code> if this ciudades is estado; <code>false</code> otherwise
	 */
	public boolean isEstado();

	/**
	 * Sets whether this ciudades is estado.
	 *
	 * @param estado the estado of this ciudades
	 */
	public void setEstado(boolean estado);

}