/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dbsystem.cotizatuvehiculo.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ClienteVehiculo service. Represents a row in the &quot;dbsystem_ClienteVehiculo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dbsystem.cotizatuvehiculo.model.impl.ClienteVehiculoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dbsystem.cotizatuvehiculo.model.impl.ClienteVehiculoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClienteVehiculo
 * @generated
 */
@ProviderType
public interface ClienteVehiculoModel extends BaseModel<ClienteVehiculo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cliente vehiculo model instance should use the {@link ClienteVehiculo} interface instead.
	 */

	/**
	 * Returns the primary key of this cliente vehiculo.
	 *
	 * @return the primary key of this cliente vehiculo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cliente vehiculo.
	 *
	 * @param primaryKey the primary key of this cliente vehiculo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cliente vehiculo ID of this cliente vehiculo.
	 *
	 * @return the cliente vehiculo ID of this cliente vehiculo
	 */
	public long getClienteVehiculoId();

	/**
	 * Sets the cliente vehiculo ID of this cliente vehiculo.
	 *
	 * @param clienteVehiculoId the cliente vehiculo ID of this cliente vehiculo
	 */
	public void setClienteVehiculoId(long clienteVehiculoId);

	/**
	 * Returns the cliente ID of this cliente vehiculo.
	 *
	 * @return the cliente ID of this cliente vehiculo
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this cliente vehiculo.
	 *
	 * @param clienteId the cliente ID of this cliente vehiculo
	 */
	public void setClienteId(long clienteId);

	/**
	 * Returns the concesionario ID of this cliente vehiculo.
	 *
	 * @return the concesionario ID of this cliente vehiculo
	 */
	public long getConcesionarioId();

	/**
	 * Sets the concesionario ID of this cliente vehiculo.
	 *
	 * @param concesionarioId the concesionario ID of this cliente vehiculo
	 */
	public void setConcesionarioId(long concesionarioId);

	/**
	 * Returns the vehiculo ID of this cliente vehiculo.
	 *
	 * @return the vehiculo ID of this cliente vehiculo
	 */
	public long getVehiculoId();

	/**
	 * Sets the vehiculo ID of this cliente vehiculo.
	 *
	 * @param vehiculoId the vehiculo ID of this cliente vehiculo
	 */
	public void setVehiculoId(long vehiculoId);

}