/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dbsystem.cotizatuvehiculo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Concesionario service. Represents a row in the &quot;dbsystem_Concesionario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dbsystem.cotizatuvehiculo.model.impl.ConcesionarioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dbsystem.cotizatuvehiculo.model.impl.ConcesionarioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Concesionario
 * @generated
 */
@ProviderType
public interface ConcesionarioModel extends BaseModel<Concesionario> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a concesionario model instance should use the {@link Concesionario} interface instead.
	 */

	/**
	 * Returns the primary key of this concesionario.
	 *
	 * @return the primary key of this concesionario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this concesionario.
	 *
	 * @param primaryKey the primary key of this concesionario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the concesionario ID of this concesionario.
	 *
	 * @return the concesionario ID of this concesionario
	 */
	public long getConcesionarioId();

	/**
	 * Sets the concesionario ID of this concesionario.
	 *
	 * @param concesionarioId the concesionario ID of this concesionario
	 */
	public void setConcesionarioId(long concesionarioId);

	/**
	 * Returns the ciudad ID of this concesionario.
	 *
	 * @return the ciudad ID of this concesionario
	 */
	public long getCiudadId();

	/**
	 * Sets the ciudad ID of this concesionario.
	 *
	 * @param ciudadId the ciudad ID of this concesionario
	 */
	public void setCiudadId(long ciudadId);

	/**
	 * Returns the concesionario of this concesionario.
	 *
	 * @return the concesionario of this concesionario
	 */
	@AutoEscape
	public String getConcesionario();

	/**
	 * Sets the concesionario of this concesionario.
	 *
	 * @param concesionario the concesionario of this concesionario
	 */
	public void setConcesionario(String concesionario);

	/**
	 * Returns the estado of this concesionario.
	 *
	 * @return the estado of this concesionario
	 */
	public boolean getEstado();

	/**
	 * Returns <code>true</code> if this concesionario is estado.
	 *
	 * @return <code>true</code> if this concesionario is estado; <code>false</code> otherwise
	 */
	public boolean isEstado();

	/**
	 * Sets whether this concesionario is estado.
	 *
	 * @param estado the estado of this concesionario
	 */
	public void setEstado(boolean estado);

}