/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dbsystem.cotizatuvehiculo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Vehiculo service. Represents a row in the &quot;dbsystem_Vehiculo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dbsystem.cotizatuvehiculo.model.impl.VehiculoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dbsystem.cotizatuvehiculo.model.impl.VehiculoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vehiculo
 * @generated
 */
@ProviderType
public interface VehiculoModel extends BaseModel<Vehiculo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vehiculo model instance should use the {@link Vehiculo} interface instead.
	 */

	/**
	 * Returns the primary key of this vehiculo.
	 *
	 * @return the primary key of this vehiculo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vehiculo.
	 *
	 * @param primaryKey the primary key of this vehiculo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vehiculo ID of this vehiculo.
	 *
	 * @return the vehiculo ID of this vehiculo
	 */
	public long getVehiculoId();

	/**
	 * Sets the vehiculo ID of this vehiculo.
	 *
	 * @param vehiculoId the vehiculo ID of this vehiculo
	 */
	public void setVehiculoId(long vehiculoId);

	/**
	 * Returns the vehiculo of this vehiculo.
	 *
	 * @return the vehiculo of this vehiculo
	 */
	@AutoEscape
	public String getVehiculo();

	/**
	 * Sets the vehiculo of this vehiculo.
	 *
	 * @param vehiculo the vehiculo of this vehiculo
	 */
	public void setVehiculo(String vehiculo);

	/**
	 * Returns the estado of this vehiculo.
	 *
	 * @return the estado of this vehiculo
	 */
	public boolean getEstado();

	/**
	 * Returns <code>true</code> if this vehiculo is estado.
	 *
	 * @return <code>true</code> if this vehiculo is estado; <code>false</code> otherwise
	 */
	public boolean isEstado();

	/**
	 * Sets whether this vehiculo is estado.
	 *
	 * @param estado the estado of this vehiculo
	 */
	public void setEstado(boolean estado);

}